import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
// store
import { FirebaseContextProvider, userAuth } from '../FirebaseProvider';
import { Provider } from 'react-redux';

import { ToastContainer, toast } from 'react-toastify';

import 'react-toastify/dist/ReactToastify.css';
import CardList from '@/components/CardList';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { username: string };
}>) {
  const { user } = userAuth();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <FirebaseContextProvider>
          {children}
          <CardList />
          <ToastContainer />
        </FirebaseContextProvider>
      </body>
    </html>
  );
}
